name: "Instagram RSS"
author: "@katydecorah"
description: "Generate an RSS feed from a list of public Instagram accounts"
runs:
  using: node16
  main: dist/index.js

inputs:
  yourInstagram:
    description: "Your Instagram username. This is required for authentication with the Instagram API."
    required: true
  listOfInstagrams:
    description: "Public Instagram usernames comma delimited."
    required: true
  fileName:
    description: "The name of the JSON feed file name to be written."
    default: "instagram.json"
  feedTitle:
    description: "The title of the RSS feed. This will appear as the title of the feed in your RSS reader."
    default: "Instagram"
  pretty:
    description: "Remove hashtags and emoji from captions."
    default: true
